# Розширена українська локалізація анатомічних та медичних термінів
# Extended Ukrainian Localization of Anatomical and Medical Terms
# Відповідно до стандартів МОЗ України та міжнародних класифікацій
# According to Ukrainian Ministry of Health standards and international classifications

# =============================================================================
# АНАТОМІЧНІ ЛОКАЛІЗАЦІЇ / ANATOMICAL LOCATIONS
# =============================================================================

# Базові терміни (індекс 0-18)
Anatomic_Index:
  0: 'brain'
  1: 'breast'
  2: 'bladder'
  3: 'kidney'
  4: 'prostate'
  5: 'testis'
  6: 'lung'
  7: 'pancreas'
  8: 'liver'
  9: 'skin'
  10: 'ovary'
  11: 'cervix'
  12: 'uterus'
  13: 'colon'
  14: 'esophagus'
  15: 'stomach'
  16: 'thyroid'
  17: 'adrenal gland'
  18: 'soft tissue'

# =============================================================================
# УКРАЇНСЬКА МЕДИЧНА НОМЕНКЛАТУРА
# Ukrainian Medical Nomenclature
# =============================================================================

Anatomic_Ukrainian_Official:
  0:
    official: 'головний мозок'           # Офіційна назва МОЗ
    latin: 'encephalon, cerebrum'        # Terminologia Anatomica
    synonyms:                             # Синоніми
      - 'мозок'
      - 'ЦНС (частина)'
      - 'головний мозок людини'
    icd11: '8A00'                        # МКХ-11 код розділу
    topography: 'ЦНС, черепна порожнина' # Топографія

  1:
    official: 'молочна залоза'
    latin: 'mamma, glandula mammaria'
    synonyms:
      - 'груди'
      - 'грудна залоза'
    icd11: 'XA4RE9'
    topography: 'передня грудна стінка'

  2:
    official: 'сечовий міхур'
    latin: 'vesica urinaria'
    synonyms:
      - 'міхур'
      - 'сечовий резервуар'
    icd11: '2C94'
    topography: 'мала таз'

  3:
    official: 'нирка'
    latin: 'ren, nephros'
    synonyms:
      - 'нирки'
      - 'нирковий орган'
    icd11: '2C90'
    topography: 'заочеревинний простір'

  4:
    official: 'передміхурова залоза'
    latin: 'prostata, glandula prostatica'
    synonyms:
      - 'простата'
      - 'передстательна залоза'
    icd11: '2C82'
    topography: 'мала таз, під сечовим міхуром'

  5:
    official: 'яєчко'
    latin: 'testis, orchis'
    synonyms:
      - 'яєчко чоловіче'
      - 'тестикул'
    icd11: '2C80'
    topography: 'мошонка'

  6:
    official: 'легеня'
    latin: 'pulmo'
    synonyms:
      - 'легені'
      - 'дихальний орган'
    icd11: '2C3Z'
    topography: 'грудна порожнина'

  7:
    official: 'підшлункова залоза'
    latin: 'pancreas'
    synonyms:
      - 'панкреас'
      - 'залоза підшлункова'
    icd11: '2C84'
    topography: 'черевна порожнина, заочеревинно'

  8:
    official: 'печінка'
    latin: 'hepar'
    synonyms:
      - 'печінка людини'
    icd11: '2C85'
    topography: 'черевна порожнина, правий верхній квадрант'

  9:
    official: 'шкіра'
    latin: 'cutis, derma'
    synonyms:
      - 'шкірні покриви'
      - 'дерма'
      - 'епідерміс і дерма'
    icd11: 'XA1SE8'
    topography: 'зовнішні покриви тіла'

  10:
    official: 'яєчник'
    latin: 'ovarium'
    synonyms:
      - 'яєчник жіночий'
      - 'оваріум'
    icd11: '2C73'
    topography: 'мала таз'

  11:
    official: 'шийка матки'
    latin: 'cervix uteri'
    synonyms:
      - 'цервікс'
      - 'шийка'
    icd11: '2C77'
    topography: 'мала таз'

  12:
    official: 'матка'
    latin: 'uterus, metra'
    synonyms:
      - 'матка жіноча'
    icd11: '2C76'
    topography: 'мала таз'

  13:
    official: 'товста кишка'
    latin: 'intestinum crassum, colon'
    synonyms:
      - 'ободова кишка'
      - 'колон'
    icd11: '2C88'
    topography: 'черевна порожнина'

  14:
    official: 'стравохід'
    latin: 'esophagus, oesophagus'
    synonyms:
      - 'езофагус'
    icd11: '2C86'
    topography: 'грудна порожнина, заочеревинно'

  15:
    official: 'шлунок'
    latin: 'ventriculus, gaster'
    synonyms:
      - 'гастер'
      - 'шлунок людини'
    icd11: '2C87'
    topography: 'черевна порожнина'

  16:
    official: 'щитоподібна залоза'
    latin: 'glandula thyroidea'
    synonyms:
      - 'щитовидна залоза'
      - 'тиреоїдна залоза'
    icd11: '2C10'
    topography: 'шия, передня ділянка'

  17:
    official: 'надниркова залоза'
    latin: 'glandula suprarenalis, glandula adrenalis'
    synonyms:
      - 'надниркова'
      - 'адреналова залоза'
    icd11: '2C12'
    topography: 'заочеревинний простір, над нирками'

  18:
    official: 'м\'які тканини'
    latin: 'textus mollis'
    synonyms:
      - 'м\'якотканинні структури'
      - 'м\'які тканини тіла'
    icd11: 'XA0N21'
    topography: 'різні локалізації'

# =============================================================================
# ОНКОЛОГІЧНА НОМЕНКЛАТУРА (МКХ-11)
# Oncological Nomenclature (ICD-11)
# =============================================================================

Cancer_Types_ICD11:
  brain:
    code: '2A00'
    name_uk: 'злоякісні новоутворення головного мозку'
    name_en: 'Malignant neoplasms of brain'
    subcategories:
      - code: '2A00.0'
        name: 'гліома'
      - code: '2A00.1'
        name: 'менінгіома злоякісна'
      - code: '2A00.Y'
        name: 'інші злоякісні новоутворення головного мозку'

  breast:
    code: '2C60'
    name_uk: 'злоякісні новоутворення молочної залози'
    name_en: 'Malignant neoplasms of breast'
    subcategories:
      - code: '2C60.0'
        name: 'карцинома молочної залози'
      - code: '2C60.1'
        name: 'дольковий рак'
      - code: '2C60.2'
        name: 'протоковий рак'

  lung:
    code: '2C25'
    name_uk: 'злоякісні новоутворення легені'
    name_en: 'Malignant neoplasms of lung'
    subcategories:
      - code: '2C25.0'
        name: 'недрібноклітинний рак легені'
      - code: '2C25.1'
        name: 'дрібноклітинний рак легені'
      - code: '2C25.2'
        name: 'аденокарцинома легені'

  colon:
    code: '2B90'
    name_uk: 'злоякісні новоутворення ободової кишки'
    name_en: 'Malignant neoplasms of colon'
    subcategories:
      - code: '2B90.0'
        name: 'аденокарцинома товстої кишки'
      - code: '2B90.1'
        name: 'карцинома сліпої кишки'

# =============================================================================
# ГІСТОЛОГІЧНІ ТИПИ (згідно WHO Classification)
# Histological Types (according to WHO Classification)
# =============================================================================

Histological_Types:
  carcinoma:
    uk: 'карцинома'
    lat: 'carcinoma'
    description: 'злоякісна пухлина епітеліального походження'
    snomed: '68453008'

  adenocarcinoma:
    uk: 'аденокарцинома'
    lat: 'adenocarcinoma'
    description: 'залозистий рак'
    snomed: '35917007'

  squamous_cell_carcinoma:
    uk: 'плоскоклітинна карцинома'
    lat: 'carcinoma planocellulare'
    description: 'рак з плоского епітелію'
    snomed: '402815007'

  sarcoma:
    uk: 'саркома'
    lat: 'sarcoma'
    description: 'злоякісна пухлина мезенхімального походження'
    snomed: '424952003'

  melanoma:
    uk: 'меланома'
    lat: 'melanoma'
    description: 'злоякісна пухлина меланоцитів'
    snomed: '372244006'

  lymphoma:
    uk: 'лімфома'
    lat: 'lymphoma'
    description: 'злоякісна пухлина лімфоїдної тканини'
    snomed: '118600007'

# =============================================================================
# СТУПІНЬ ДИФЕРЕНЦІЮВАННЯ (Grade)
# Differentiation Grade
# =============================================================================

Tumor_Grade:
  G1:
    uk: 'високодиференційована'
    description: 'добре диференційована пухлина'
  G2:
    uk: 'помірно диференційована'
    description: 'помірний ступінь диференціювання'
  G3:
    uk: 'низькодиференційована'
    description: 'погано диференційована пухлина'
  G4:
    uk: 'недиференційована'
    description: 'анапластична пухлина'
  GX:
    uk: 'ступінь не визначено'
    description: 'неможливо оцінити ступінь диференціювання'

# =============================================================================
# TNM КЛАСИФІКАЦІЯ (українською)
# TNM Classification (Ukrainian)
# =============================================================================

TNM_Staging:
  T:
    name: 'первинна пухлина'
    values:
      TX: 'первинна пухлина не може бути оцінена'
      T0: 'ознак первинної пухлини немає'
      Tis: 'карцинома in situ (преінвазивна карцинома)'
      T1: 'пухлина обмежена органом, невеликого розміру'
      T2: 'пухлина більшого розміру, але в межах органу'
      T3: 'пухлина поширюється за межі органу'
      T4: 'пухлина проростає сусідні структури'

  N:
    name: 'регіонарні лімфатичні вузли'
    values:
      NX: 'регіонарні лімфовузли не можуть бути оцінені'
      N0: 'метастазів у регіонарних лімфовузлах немає'
      N1: 'метастази в одиничних регіонарних лімфовузлах'
      N2: 'метастази у множинних регіонарних лімфовузлах'
      N3: 'масивне ураження лімфовузлів'

  M:
    name: 'віддалені метастази'
    values:
      M0: 'віддалених метастазів немає'
      M1: 'віддалені метастази виявлені'
      MX: 'віддалені метастази не можуть бути оцінені'

# =============================================================================
# СТАДІЇ ЗАХВОРЮВАННЯ
# Disease Stages
# =============================================================================

Cancer_Stages:
  stage_0:
    uk: 'стадія 0'
    description: 'рак in situ (на місці)'
    prognosis: 'найкращий прогноз'

  stage_I:
    uk: 'стадія I'
    description: 'рання стадія, локалізована пухлина'
    prognosis: 'хороший прогноз'

  stage_II:
    uk: 'стадія II'
    description: 'місцево-поширений рак'
    prognosis: 'помірний прогноз'

  stage_III:
    uk: 'стадія III'
    description: 'поширення на регіонарні лімфовузли'
    prognosis: 'обережний прогноз'

  stage_IV:
    uk: 'стадія IV'
    description: 'метастатичний рак, віддалені метастази'
    prognosis: 'несприятливий прогноз'

# =============================================================================
# МЕДИЧНІ ВИСНОВКИ (стандартні формулювання)
# Medical Conclusions (standard formulations)
# =============================================================================

Diagnosis_Templates:
  malignant:
    uk: 'Виявлено морфологічні ознаки злоякісного новоутворення'
    confidence_high: 'з високою ймовірністю'
    confidence_moderate: 'з помірною ймовірністю'
    confidence_low: 'з низькою ймовірністю'

  benign:
    uk: 'Виявлено морфологічні ознаки доброякісного новоутворення'

  suspicious:
    uk: 'Виявлено підозрілі морфологічні зміни, що потребують додаткового дослідження'

  normal:
    uk: 'Грубих морфологічних змін не виявлено'

  inflammatory:
    uk: 'Виявлено ознаки запального процесу'

# =============================================================================
# ТЕРМІНОЛОГІЯ ДЛЯ ЗВІТІВ (МОЗ України)
# Terminology for Reports (Ukrainian MOH)
# =============================================================================

Report_Terminology:
  patient_info:
    anonymous_id: 'Анонімний ідентифікатор пацієнта'
    gender: 'Стать'
    age: 'Вік'

  specimen_info:
    slide_id: 'Номер препарату'
    collection_date: 'Дата забору матеріалу'
    fixation: 'Фіксація'
    staining: 'Забарвлення'
    scanner: 'Сканер'
    magnification: 'Збільшення'

  analysis_info:
    analysis_date: 'Дата аналізу'
    model_version: 'Версія моделі'
    confidence: 'Впевненість моделі'

  conclusion:
    diagnosis: 'Висновок'
    recommendation: 'Рекомендації'
    disclaimer: 'Застереження'

# =============================================================================
# СЕРТИФІКАЦІЙНА ТЕРМІНОЛОГІЯ
# Certification Terminology
# =============================================================================

Certification:
  regulatory:
    ukraine:
      body: 'Міністерство охорони здоров\'я України'
      law: 'Основи законодавства України про охорону здоров\'я'
      data_protection: 'Закон України "Про захист персональних даних"'
      medical_devices: 'Технічний регламент медичних виробів'

  quality_standards:
    iso_13485: 'ISO 13485 - Медичні вироби. Системи управління якістю'
    iso_27001: 'ISO 27001 - Інформаційна безпека'
    gdpr: 'GDPR - Загальний регламент захисту даних (застосовується частково)'

  validation:
    clinical: 'Клінічна валідація'
    technical: 'Технічна валідація'
    analytical: 'Аналітична валідація'

  intended_use:
    uk: 'Призначення для використання'
    description: |
      Допоміжна система для аналізу гістопатологічних зображень.
      НЕ є заміною рішення кваліфікованого патологоанатома.
      Використовується для підтримки прийняття клінічних рішень.

# =============================================================================
# СТАНДАРТНІ СКОРОЧЕННЯ
# Standard Abbreviations
# =============================================================================

Abbreviations:
  medical:
    ГП: 'гістопатологічне дослідження'
    МКХ: 'Міжнародна класифікація хвороб'
    ШІ: 'штучний інтелект'
    МОЗ: 'Міністерство охорони здоров\'я'
    ЛПУ: 'лікувально-профілактична установа'
    АРМ: 'автоматизоване робоче місце'
    ЦПР: 'цифрове патоморфологічне дослідження'

  technical:
    WSI: 'whole-slide imaging (зображення цілого слайду)'
    ROI: 'region of interest (область інтересу)'
    H&E: 'гематоксилін та еозин (забарвлення)'
    IHC: 'імуногістохімія'
    FISH: 'флуоресцентна гібридизація in situ'

# =============================================================================
# ВЕРСІЯ ТА МЕТАДАНІ
# Version and Metadata
# =============================================================================

Metadata:
  version: '2.0'
  date: '2025-11-17'
  author: 'CHIEF Ukraine Adaptation Team'
  standard: 'МОЗ України, МКХ-11, SNOMED CT, WHO Classification'
  language: 'uk_UA'
  encoding: 'UTF-8'
