# Українська локалізація анатомічних термінів
# Ukrainian localization of anatomical terms
# Для використання в CHIEF моделі / For use in CHIEF model

Anatomic:
    # Оригінальна англійська назва: українська назва
    'brain': 0        # Головний мозок
    'breast': 1       # Молочна залоза
    'bladder': 2      # Сечовий міхур
    'kidney': 3       # Нирка
    'prostate': 4     # Передміхурова залоза
    'testis': 5       # Яєчко
    'lung': 6         # Легеня
    'pancreas': 7     # Підшлункова залоза
    'liver': 8        # Печінка
    'skin': 9         # Шкіра
    'ovary': 10       # Яєчник
    'cervix': 11      # Шийка матки
    'uterus': 12      # Матка
    'colon': 13       # Товста кишка
    'esophagus': 14   # Стравохід
    'stomach': 15     # Шлунок
    'thyroid': 16     # Щитоподібна залоза
    'adrenal gland': 17  # Надниркова залоза
    'soft tissue': 18    # М'які тканини

# Додаткова інформація для української локалізації
# Additional information for Ukrainian localization

Anatomic_Ukrainian:
    'головний мозок': 0
    'молочна залоза': 1
    'сечовий міхур': 2
    'нирка': 3
    'передміхурова залоза': 4
    'яєчко': 5
    'легеня': 6
    'підшлункова залоза': 7
    'печінка': 8
    'шкіра': 9
    'яєчник': 10
    'шийка матки': 11
    'матка': 12
    'товста кишка': 13
    'стравохід': 14
    'шлунок': 15
    'щитоподібна залоза': 16
    'надниркова залоза': 17
    'м\'які тканини': 18

# Мапінг для медичних термінів
Medical_Terms_Mapping:
    'brain_tumor': 'пухлина головного мозку'
    'breast_cancer': 'рак молочної залози'
    'bladder_cancer': 'рак сечового міхура'
    'kidney_cancer': 'рак нирки'
    'prostate_cancer': 'рак передміхурової залози'
    'testicular_cancer': 'рак яєчка'
    'lung_cancer': 'рак легені'
    'pancreatic_cancer': 'рак підшлункової залози'
    'liver_cancer': 'рак печінки'
    'skin_cancer': 'рак шкіри'
    'ovarian_cancer': 'рак яєчника'
    'cervical_cancer': 'рак шийки матки'
    'uterine_cancer': 'рак матки'
    'colon_cancer': 'рак товстої кишки'
    'esophageal_cancer': 'рак стравоходу'
    'gastric_cancer': 'рак шлунку'
    'thyroid_cancer': 'рак щитоподібної залози'
    'adrenal_cancer': 'рак надниркової залози'
    'soft_tissue_sarcoma': 'саркома м\'яких тканин'
